package com.example.administrator.onetotwo.main.generator;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "USER".
 */
public class User {

    /** Not-null value. */
    private String objectId;
    private String username;
    private String password;
    private String mobilePhoneNumber;
    private String email;

    public User() {
    }

    public User(String objectId) {
        this.objectId = objectId;
    }

    public User(String objectId, String username, String password, String mobilePhoneNumber, String email) {
        this.objectId = objectId;
        this.username = username;
        this.password = password;
        this.mobilePhoneNumber = mobilePhoneNumber;
        this.email = email;
    }

    /** Not-null value. */
    public String getObjectId() {
        return objectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getMobilePhoneNumber() {
        return mobilePhoneNumber;
    }

    public void setMobilePhoneNumber(String mobilePhoneNumber) {
        this.mobilePhoneNumber = mobilePhoneNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
